
;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2018/7/2 12:04:40

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.
